apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kubectl
    image: joshendriks/alpine-k8s
    command:
    - /bin/cat
    tty: true    
  - name: mulki12
    image: gcr.io/kaniko-project/executor:debug
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: mulki-secret
        mountPath: /mulki/.docker
  volumes:
    - name: mulki-secret
      secret:
        secretName: regcred
        items:
          - key: .dockerconfigjson
            path: config.json
